services:
  - type: web
    name: citaya-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn citaya.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: citaya-db
          property: connectionString
      - key: RENDER_EXTERNAL_HOSTNAME
        value: ""  # Render lo inyecta automáticamente

databases:
  - name: citaya-db
    plan: free
    databaseName: citaya_db
    user: citaya_user
