# Generated by Django 4.2 on 2026-03-22 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id_agendamiento', models.AutoField(primary_key=True, serialize=False)),
                ('cita', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.paciente')),
            ],
        ),
    ]
