# Generated by Django 4.2 on 2026-03-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_agendamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Clinico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('antecedentes', models.TextField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.paciente')),
            ],
        ),
    ]
