# Generated by Django 4.2 on 2026-04-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_historial_clinico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medico',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
    ]
