# Generated by Django 4.2 on 2026-05-21 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_administrador_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Médico'), ('paciente', 'Paciente')], max_length=10)),
                ('usuario_id', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
    ]
