# Generated by Django 4.2 on 2026-06-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
