# Generated by Django 4.2 on 2026-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicos/fotos/'),
        ),
    ]
